name: Tycoon
version: '1.0-SNAPSHOT'
main: org.kimgooner.tycoon.Tycoon
api-version: '1.21'
commands:
  mining:
    description: 채광 명령어
    usage: /mining <subcommand>
  heart:
    description: 동굴의 심장 명령어
    usage: /heart <subcommand>
